opt_out_usage

#######################################################################
# Lifecycle Hooks
#######################################################################

before_all do
#    reset_simulators
end

after_all do |lane|
    # This block is called, only if the executed lane was successful
end

error do |lane, exception|
end

#######################################################################
# Lanes
#######################################################################

desc "Perform the build steps on travis CI"
lane :travis do
  macOS
  iOS
  tvOS
  validate_cocoapods
  validate_carthage
end

desc "Build Freddy for macOS"
lane :macOS do
  scan(scheme: "Freddy")
end

desc "Build Freddy for iOS"
lane :iOS do
  device_id = sh("xcrun simctl create TestingiPhone5 com.apple.CoreSimulator.SimDeviceType.iPhone-5 com.apple.CoreSimulator.SimRuntime.iOS-10-0")
  puts "device_id: #{device_id}"
  sh("open -a /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app/ --args -CurrentDeviceUDID #{device_id}")
  scan(scheme: "MobileFreddy", device: "TestingiPhone5")
end

desc "Build Freddy for tvOS"
lane :tvOS do
  device_id = sh("xcrun simctl create TestTV com.apple.CoreSimulator.SimDeviceType.Apple-TV-1080p com.apple.CoreSimulator.SimRuntime.tvOS-10-0")
  puts "device_id: #{device_id}"
  sh("open -a /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app/ --args -CurrentDeviceUDID #{device_id}")
  scan(scheme: "TVFreddy", device: "TestTV")
end

desc "Validate cocoapods podspec file"
lane :validate_cocoapods do
  pod_lib_lint(quick: true)
end

desc "Validate carthage build"
lane :validate_carthage do
  if is_ci?
    system("./Resources/scripts/validate_carthage.sh")
  else
    puts "This is a CI only lane, skipping"
  end
end

desc "Create docs"
lane :create_docs do
  ## TODO: Implement once jazzy is working well for Xcode 8
  if is_ci?
    #system("./Resources/scripts/publish_docs.sh")
    puts "Would be creating docs here"
  else
    puts "This is a CI only lane, skipping"
  end
end

desc "Test testing"
lane :test_testing do
  device_id = sh("xcrun simctl create TestingiPhone5 com.apple.CoreSimulator.SimDeviceType.iPhone-5 com.apple.CoreSimulator.SimRuntime.iOS-10-0")
  puts "device_id: #{device_id}"
  sh("open -a /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app/ --args -CurrentDeviceUDID #{device_id}")

#  sh("xcrun simctl boot TestingiPhone5")
  scan(scheme: "MobileFreddy", device: "TestingiPhone5")
  # sh("xcrun simctl shutdown TestingiPhone5")
  # sh("xcrun simctl delete TestingiPhone5")

#  sh("xcrun simctl create TestTV com.apple.CoreSimulator.SimDeviceType.Apple-TV-1080p com.apple.CoreSimulator.SimRuntime.tvOS-10-0")
#  sh("xcrun simctl boot TestTV")
#  scan(scheme: "TVFreddy", device: "TestTV")
end
